    - name: Nettoyer le projet Gradle
      run: ./gradlew clean --no-daemon
      working-directory: android # Soloy ny anaran'ny folder-nao raha tsy android

    - name: Créer l'APK TSENA MALAGASY
      run: ./gradlew assembleDebug --no-daemon --no-configuration-cache
      working-directory: android # Soloy ny anaran'ny folder-nao raha tsy android
